// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyEpOPxGDVjHeZ_6di67FHuau3rJOgdr4',
    appId: '1:833995100698:web:339b05096a56d21b8bf7a3',
    messagingSenderId: '833995100698',
    projectId: 'chat-app-7a69b',
    authDomain: 'chat-app-7a69b.firebaseapp.com',
    storageBucket: 'chat-app-7a69b.firebasestorage.app',
    measurementId: 'G-8G250ZKJ3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoCiGLiur7tUjXkMb74bu_ZU2_J52EcE',
    appId: '1:833995100698:android:0cfd5ebc5ab516858bf7a3',
    messagingSenderId: '833995100698',
    projectId: 'chat-app-7a69b',
    storageBucket: 'chat-app-7a69b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABl8BusLzMwjHdW3MQ-Wdep2Dddzk1nU8',
    appId: '1:833995100698:ios:87c4b4cce21ab3388bf7a3',
    messagingSenderId: '833995100698',
    projectId: 'chat-app-7a69b',
    storageBucket: 'chat-app-7a69b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABl8BusLzMwjHdW3MQ-Wdep2Dddzk1nU8',
    appId: '1:833995100698:ios:87c4b4cce21ab3388bf7a3',
    messagingSenderId: '833995100698',
    projectId: 'chat-app-7a69b',
    storageBucket: 'chat-app-7a69b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyEpOPxGDVjHeZ_6di67FHuau3rJOgdr4',
    appId: '1:833995100698:web:826890668cd5757b8bf7a3',
    messagingSenderId: '833995100698',
    projectId: 'chat-app-7a69b',
    authDomain: 'chat-app-7a69b.firebaseapp.com',
    storageBucket: 'chat-app-7a69b.firebasestorage.app',
    measurementId: 'G-NS9C3Y2T8H',
  );
}
